// Correspond à la classe java ca.qc.gouv.msss.sigct.infosante.enums.FicheAppelPage
export enum FicheAppelPageEnum {
  PAGE_DEMANDE_EVALUATION = "PAGE_DEMANDE_EVALUATION", //
  PAGE_INTERVENTION = "PAGE_INTERVENTION",//
  PAGE_TERMINAISON = "PAGE_TERMINAISON",//
  PAGE_USAGER_APPELANT = "PAGE_USAGER_APPELANT", //
  PAGE_SAISIE_DIFFEREE = "PAGE_SAISIE_DIFFEREE",
}
